<?php

/**
 * @file
 * Hooks and functionality for the Group Commerce Order module.
 *
 * @I Implement group access control
 *    type     : bug
 *    priority : high
 *    labels   : security
 */

use Drupal\commerce_order\Entity\OrderTypeInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * Clear the cached group content enabler plugin definitions when a new order
 * type is created so that it can be recognized without having to rebuild
 * caches.
 */
function gcommerce_order_commerce_order_type_insert(
  OrderTypeInterface $order_type
) {
  \Drupal::service('plugin.manager.group_content_enabler')
    ->clearCachedDefinitions();
}
